[room]
room_name = "room-2121"
username = "mk"
priv_key = "IBXInFjefNHcYHt7yIXz9rpMEU/iqiKiyulbFJHtlVk="

[interface]
interface_name = "cnrs-room-212"

[addrs]
stun_addr = "stun.1und1.de:3478"
server_addr = "https://server.mishakulik2.workers.dev/"
redis_addr = "rediss://client:08794a557c35bd6449abc35ed8d3128930daa4600a87a768ca79848ee31760c3@balanced-mastiff-35201.upstash.io:35201"
